#ifndef _XILLEONINT_H
#define _XILLEONINT_H

/* INTS 0-7 are MIPS */
#define MIPS_IRQBASE			0
#define NUM_MIPS_IRQS			8

#define XILLEON_CP0_TIMER_INT		(MIPS_IRQBASE + 7)	/* 7 */

/* INTS 8-31 are SB */
#define SB_IRQBASE			8
#define NUM_SB_IRQS			24

#define XILLEON_USB_INT			(SB_IRQBASE + 1)	/* 9 */
#define XILLEON_IDE0_INT		(SB_IRQBASE + 2)	/* 10 */
#define XILLEON_IDE1_INT		(SB_IRQBASE + 3)	/* 11 */
#define XILLEON_DAIO0_INT		(SB_IRQBASE + 8)	/* 16 */
#define XILLEON_DAIO1_INT		(SB_IRQBASE + 9)	/* 17 */
#define XILLEON_MBA_INT			(SB_IRQBASE + 10)	/* 18 */

/* INTS 33-64 are EXT_PCI */
#define EXT_PCI_IRQBASE			33
#define NUM_EXT_PCI_IRQS		32

#define XILLEON_INTR0_INT		(EXT_PCI_IRQBASE + 0)	/* 33 */
#define XILLEON_INTR1_INT		(EXT_PCI_IRQBASE + 1)	/* 34 */
#define XILLEON_INTR2_INT		(EXT_PCI_IRQBASE + 2)	/* 35 */
#define XILLEON_INTR3_INT		(EXT_PCI_IRQBASE + 3)	/* 36 */

/* INTS 65-96 are GEN */
#define GEN_IRQBASE			65
#define NUM_GEN_IRQS			32

#define XILLEON_CRTC_VBLANK_INT		(GEN_IRQBASE + 0)	/* 65 */
#define XILLEON_CRTC_VLINE_INT		(GEN_IRQBASE + 1)	/* 66 */
#define XILLEON_CRTC_VSYNC_INT		(GEN_IRQBASE + 2)	/* 67 */
#define XILLEON_SNAPSHOT_INT		(GEN_IRQBASE + 3)	/* 68 */
#define XILLEON_HM_COM_MIPS_INT		(GEN_IRQBASE + 4)	/* 69 */
#define XILLEON_HM_COM_CPU_INT		(GEN_IRQBASE + 5)	/* 70 */
#define XILLEON_TPS_MIPS_INT		(GEN_IRQBASE + 6)	/* 71 */
#define XILLEON_TPS_CPU_INT		(GEN_IRQBASE + 7)	/* 72 */
#define XILLEON_VIDCAP_INT		(GEN_IRQBASE + 8)	/* 73 */
#define XILLEON_MPEG1_INT		(GEN_IRQBASE + 9)	/* 74 */
#define XILLEON_MPEG_INT		(GEN_IRQBASE + 10)	/* 75 */
#define XILLEON_FP2_DETECT_INT		(GEN_IRQBASE + 11)	/* 76 */
#define XILLEON_VLB_OP_INT		(GEN_IRQBASE + 12)	/* 77 */
#define XILLEON_EXT_I2C_DATA_REQ_INT	(GEN_IRQBASE + 14)	/* 79 */
#define XILLEON_PCU_INT			(GEN_IRQBASE + 15)	/* 80 */
#define XILLEON_BUSMASTER_EOL_INT	(GEN_IRQBASE + 16)	/* 81 */
#define XILLEON_CRTC_VBLANK_BIT2_INT	(GEN_IRQBASE + 17)	/* 82 */
#define XILLEON_CRTC1_VBLANK_BIT2_INT	(GEN_IRQBASE + 18)	/* 83 */
#define XILLEON_SI_MIPS_INT		(GEN_IRQBASE + 20)	/* 85 */
#define XILLEON_SI_CPU_INT		(GEN_IRQBASE + 21)	/* 86 */
#define XILLEON_AUDIO_INT		(GEN_IRQBASE + 22)	/* 87 */
#define XILLEON_PCIC_INT		(GEN_IRQBASE + 23)	/* 88 */
#define XILLEON_VIPH_INT		(GEN_IRQBASE + 24)	/* 89 */
#define XILLEON_CRTC1_VBLANK_INT	(GEN_IRQBASE + 25)	/* 90 */
#define XILLEON_CRTC1_VLINE_INT		(GEN_IRQBASE + 26)	/* 91 */
#define XILLEON_CRTC1_VSYNC_INT		(GEN_IRQBASE + 27)	/* 92 */
#define XILLEON_SOUTHBRIDGE_INT		(GEN_IRQBASE + 28)	/* 93 */
#define XILLEON_SNAPSHOT1_INT		(GEN_IRQBASE + 29)	/* 94 */
#define XILLEON_CHIP_INT		(GEN_IRQBASE + 31)	/* 96 */

/* INTS 97-127 are PCU */
#define PCU_IRQBASE			97
#define NUM_PCU_IRQS			31

#define XILLEON_DMA_INT			(PCU_IRQBASE + 0)	/* 97 */
#define XILLEON_UIRT1_INT		(PCU_IRQBASE + 1)	/* 98 */
#define XILLEON_UART1_INT		(PCU_IRQBASE + 2)	/* 99 */
#define XILLEON_UART2_INT		(PCU_IRQBASE + 3)	/* 100 */
#define XILLEON_TIMER_GLOBAL_INT	(PCU_IRQBASE + 4)	/* 101 */
#define XILLEON_RTC_GLOBAL_INT		(PCU_IRQBASE + 5)	/* 102 */
#define XILLEON_FLEXBUS0_INT		(PCU_IRQBASE + 8)	/* 105 */
#define XILLEON_FLEXBUS1_INT		(PCU_IRQBASE + 9)	/* 106 */
#define XILLEON_FLEXBUS2_INT		(PCU_IRQBASE + 10)	/* 107 */
#define XILLEON_FLEXBUS3_INT		(PCU_IRQBASE + 11)	/* 108 */
#define XILLEON_FLEXBUS4_INT		(PCU_IRQBASE + 12)	/* 109 */
#define XILLEON_FLEXBUS5_INT		(PCU_IRQBASE + 13)	/* 110 */
#define XILLEON_FLEXBUS6_INT		(PCU_IRQBASE + 14)	/* 111 */
#define XILLEON_FLEXBUS7_INT		(PCU_IRQBASE + 15)	/* 112 */
#define XILLEON_I2C0_INT		(PCU_IRQBASE + 16)	/* 113 */
#define XILLEON_I2C1_INT		(PCU_IRQBASE + 17)	/* 114 */
#define XILLEON_SMCA_INT		(PCU_IRQBASE + 18)	/* 115 */
#define XILLEON_SMCB_INT		(PCU_IRQBASE + 19)	/* 116 */
#define XILLEON_SMCC_INT		(PCU_IRQBASE + 20)	/* 117 */
#define XILLEON_HDCP_AUTHORIZED_INT	(PCU_IRQBASE + 21)	/* 118 */
#define XILLEON_DVI_I2C_INT		(PCU_IRQBASE + 22)	/* 119 */
#define XILLEON_UIRT2_INT		(PCU_IRQBASE + 23)	/* 120 */
#define XILLEON_HOST_WRITE_DETECT_INT	(PCU_IRQBASE + 24)	/* 121 */
#define XILLEON_UART3_INT		(PCU_IRQBASE + 25)	/* 122 */
#define XILLEON_DVI_MSEN_INT		(PCU_IRQBASE + 26)	/* 123 */
#define XILLEON_HDCP_SW_LINK_INT	(PCU_IRQBASE + 27)	/* 124 */

#endif /* _XILLEONINT_H */
